### ISSUE TITLE
TcpFakeServer holding thread open after application executes when using Redis TimeSeries

### ISSUE THREAD

**Issue by fisher60** [cunla/fakeredis-py#409]
**Describe the bug**
Using a Redis timeseries with `TcpFakeServer` results in the application hanging open due to multiple threads spawning/running in the background.

**To Reproduce**
1. Follow the documentation [here](https://[fakeredis](https://fakeredis.readthedocs.io/en/latest/#start-a-server-on-a-thread).readthedocs.io/en/latest/#start-a-server-on-a-thread) to start a server running in a thread.
2. Connect to redis and create a redis TimeSeries client.
3. run `timeseries.add()`
4. application logic finishes, application is held open due to background threads

**Expected behavior**
It is expected that once the application finishes (i.e the timeseries.add() executes), the thread will also exit. It seems that multiple, non-daemon threads, are spawned during this action.

**Desktop (please complete the following information):**
 - OS:Widnows 11
 - Python 3.13.7
 - redis-py version:2.31.0
 ```toml
dependencies = [
    "kraken-client>=0.1.0",
    "websockets>=12.0",
    "colorlog>=6.7.0",
    "opentelemetry-api>=1.35.0",
    "opentelemetry-exporter-otlp>=1.35.0 ",
    "opentelemetry-instrumentation-logging>=0.56b0",
    "opentelemetry-sdk>=1.35.0",
    "redis>=6.4.0",
    "mock>=5.1.0",
    "pandas>=2.1.3",
    "pydantic>=2.5.2",
]
[tool.pdm.dev-dependencies]
dev = [
    "setuptools>=68.2.2",
    "pre-commit>=3.5.0",
    "ruff>=0.1.11",
    "fakeredis>=2.31.0"
]
```

**Additional context**
Example to reproduce:
```py
from threading import Thread
import time
from fakeredis import TcpFakeServer
from redis import Redis

from market_gather.datastream import Ticker


REDIS_IP = "127.0.0.1"
REDIS_PORT = 6379

REDIS_URL = f"redis://{REDIS_IP}:{REDIS_PORT}"

server_address = (REDIS_IP, REDIS_PORT)
server = TcpFakeServer(server_address, server_type="redis")
t = Thread(target=server.serve_forever, daemon=True)
t.start()

print("fake redis started")

redis: Redis = Redis.from_url(REDIS_URL)

print("creating timeseries")
timeseries = redis.ts()

timestamp = round(time.time() * 1000)

timeseries.add(
    "ticker:test:thing",
    timestamp,
    0.5,
    duplicate_policy="LAST",
    labels={"symbol": "test", "type": "thing"},
)

print("complete")
```

Output from above
```
python .\redis_test.py
fake redis started
creating timeseries
complete
```

**Comment by cunla** [comment]
You are not closing the thread you created.

Use `server.shutdown()` - that should do the trick. To be extra sure:
```python
server.shutdown() # Stop the serve_forever loop
server.server_close() # Close the server socket
t.join() # Wait for the server thread to finish

```

I updated the docs to include this information

**Comment by fisher60** [comment]
Hello, this does not resolve my issue.

I have amended my example with your instructions. This results in the application hanging indefinitely and the line `print("complete")` becoming unreachable.

```py
from threading import Thread
import time
from fakeredis import TcpFakeServer
from redis import Redis

from market_gather.datastream import Ticker


REDIS_IP = "127.0.0.1"
REDIS_PORT = 6379

REDIS_URL = f"redis://{REDIS_IP}:{REDIS_PORT}"

server_address = (REDIS_IP, REDIS_PORT)
server = TcpFakeServer(server_address, server_type="redis")
t = Thread(target=server.serve_forever, daemon=True)
t.start()

print("fake redis started")

redis: Redis = Redis.from_url(REDIS_URL)

print("creating timeseries")
timeseries = redis.ts()

timestamp = round(time.time() * 1000)

timeseries.add(
    "ticker:test:thing",
    timestamp,
    0.5,
    duplicate_policy="LAST",
    labels={"symbol": "test", "type": "thing"},
)

server.shutdown() # Stop the serve_forever loop
server.server_close() # Close the server socket
t.join() # Wait for the server thread to finish

print("complete")
```
Result: 
```
fake redis started
creating timeseries
```
